# Generated by Django 5.1.3 on 2024-12-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='TestField',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
