# Generated by Django 5.1.4 on 2024-12-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_accesskey_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesskey',
            old_name='Groups',
            new_name='Group',
        ),
    ]
