# Generated by Django 5.1.3 on 2024-12-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userinfo_testfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(default='', max_length=100)),
                ('Roles', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
