# Generated by Django 5.1.4 on 2025-01-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_groups_accesskey_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Logged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_title', models.CharField(default='no name', max_length=255)),
                ('hours_logged', models.FloatField(default=0.0)),
                ('hours_not_logged', models.FloatField(default=0.0)),
                ('people_attended', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='accesskey',
            old_name='document_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='document_id',
            new_name='id',
        ),
    ]
