# Generated by Django 5.1.4 on 2025-01-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_logged_rename_document_id_accesskey_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Logged',
            new_name='EventLogged',
        ),
    ]
