services:
  gunicorn:
    build:
      context: . # use dockerfile in this directory
      args: # passes .env file as the ENV argument
        ENV: .env
        VITEINDOCKER: "true"
  nginx:
    volumes:
      - ./nginx.testing.conf:/etc/nginx/nginx.conf