services:
  gunicorn:
    build:
      context: . # use dockerfile in this directory
      args: # passes .env file as the ENV argument
        ENV: .env
  nginx:
    # uses test nginx config (the one without ssl)
    volumes:
      - ./nginx.testing.conf:/etc/nginx/nginx.conf